version: '3.1'
services:
  springboot:
    image: vkpatilhsit/spring-boot-mongo-docker-application:latest
    restart: always
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=vkpatilhsit
    - MONGO_DB_PASSWORD=passw0rd1
    ports:
    - 8080:8080
    working_dir: /opt/app
    depends_on:
    - mongo
    networks:
    - springappnetwork  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=vkpatilhsit
    - MONGO_INITDB_ROOT_PASSWORD=passw0rd1
    volumes:
    - mongodbvol:/data/db
    networks:
    - springappnetwork
volumes:
  mongodbvol:
networks:
  springappnetwork:
    
