apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-web-application
  namespace: argocd
spec:
  destination:
    namespace: myapp
    server: https://kubernetes.default.svc
  project: 'my-applications'
  source:
    path: manifests
    repoURL: https://github.com/vkpatilhsit/spring-boot-mongodb.git
    targetRevision: master
  syncPolicy:
  - CreateNamespace=true
  automated:
    prune: true
    selfHeal: true
