---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: javawebapp
  name: java-controller
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: javawebapp
    spec:
      containers:
      - image: vkpatilhsit/spring-boot-application:1
        name: javawebapp
        ports:
        - name: javawebapp
          containerPort: 8080 
